### ISSUE TITLE
Allow symbols as collection keys 

### ISSUE THREAD

**Issue by agalazis** [noder-io/noder.io#2]
When I pass symbols to collections I get the following :

`Argument #1 passed to Collection.set() must be a string identifier`
I guess this is ass simple as updating the checks that you have in your code (there could also be a configuration in the constructor  to allow them )
The reason I want symbols is in order to have opaque keys for each dependency rather than strings that can clash.

**Comment by Nicolab** [comment]
Hello,

[Symbol().toString()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/toString) is made for that :)

**Comment by agalazis** [comment]
No, it's not made for that. Symbol().toString()  doesn't help avoid clashes eg. if  I have two different Symbols with the same key they are two different symbols but their string output is the same
In short: Symbol().toString()  beats the purpose of using symbols

**Comment by Nicolab** [comment]
You are right.

I want to preserve this package simple, lightweight and homogeneous. Integration of symbols in Collection will have an unnecessary impact on that.

[Map](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Map) can be useful for this. Otherwise you can extend the Collection class and override the methods : get, set, remove, etc

The cleanest is to add the methods: setSymbol(), getSymbol(), removeSymbol(), ... to avoid API from becoming a bit too magical.
